export class KeysName {
  static MONGODB_URL = 'MONGODB_URL';
  static WALLEX_API_URL = 'WALLEX_API_URL';
  static WALLEX_API_KEY = 'WALLEX_API_KEY';
  static WALLEX_ACCESS_KEYID = 'WALLEX_ACCESS_KEYID';
  static WALLEX_SECRET_KEY = 'WALLEX_SECRET_KEY';
  static  _JWT_SECRET = ' _JWT_SECRET';
  static  _JWT_COOKIE_DOMAIN = ' _JWT_COOKIE_DOMAIN';
  static SMTP_HOST = 'SMTP_HOST';
  static SMTP_USER = 'SMTP_USER';
  static SMTP_PASS = 'SMTP_PASS';
  static  _INVOICE_NFT_CONTRACT_ADDRESS =
    ' _INVOICE_NFT_CONTRACT_ADDRESS';
  static  _ADMIN_ADDRESS = ' _ADMIN_ADDRESS';
  static  _ADMIN_SEED_PHRASE = ' _ADMIN_SEED_PHRASE';
  static  _PINATA_URL = ' _PINATA_URL';
  static  _API_KEY = ' _API_KEY';
  static  _ENCRYPTION_KEY = ' _ENCRYPTION_KEY';
  static TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID';
  static TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN';
  static NODE_ENV = 'NODE_ENV';
  static AWS_S3_BUCKET = 'AWS_S3_BUCKET';
  static NETWORK_NAME = 'NETWORK_NAME';
  static RPC_URL = 'RPC_URL';
  static PINATA_API_KEY = 'PINATA_API_KEY';
  static PINATA_API_SECRET = 'PINATA_API_SECRET';
  static CLIENT_APP_URL = 'CLIENT_APP_URL';
  static ADMIN_APP_URL = 'ADMIN_APP_URL';
  static GOOGLE_CAPTCHA = 'GOOGLE_CAPTCHA';
  static GAS_STATION = 'GAS_STATION';
  static  _PRIVATE_KEY = ' _PRIVATE_KEY';
  static ALCHEMY_KEY = 'ALCHEMY_KEY';
}
